import debug from 'debug'

const log = debug('shinkansen-pantograph/pantograph')

log('`shinkansen` is awake')

export const ALPHA = {
  ERROR: 'ALPHA_ERROR',
  ROUTE: 'ALPHA_ROUTE',
  MOUNT: 'ALPHA_MOUNT',
  FETCH: 'ALPHA_FETCH',
  STORE: 'ALPHA_STORE',
  QUERY: 'ALPHA_QUERY',
  CHANGE: 'ALPHA_CHANGE',
  SUBMIT: 'ALPHA_SUBMIT'
}

export const OMEGA = {
  ERROR: 'OMEGA_ERROR',
  ROUTE: 'OMEGA_ROUTE',
  MOUNT: 'OMEGA_MOUNT',
  FETCH: 'OMEGA_FETCH',
  STORE: 'OMEGA_STORE',
  QUERY: 'OMEGA_QUERY',
  CHANGE: 'OMEGA_CHANGE',
  SUBMIT: 'OMEGA_SUBMIT'
}

export const EMBARK = {
  ERROR: 'EMBARK_ERROR',
  ROUTE: 'EMBARK_ROUTE',
  MOUNT: 'EMBARK_MOUNT',
  FETCH: 'EMBARK_FETCH',
  STORE: 'EMBARK_STORE',
  CHANGE: 'EMBARK_CHANGE',
  SUBMIT: 'EMBARK_SUBMIT'
}

export const DEBARK = {
  ERROR: 'DEBARK_ERROR',
  ROUTE: 'DEBARK_ROUTE',
  MOUNT: 'DEBARK_MOUNT',
  FETCH: 'DEBARK_FETCH',
  STORE: 'DEBARK_STORE',
  CHANGE: 'DEBARK_CHANGE',
  SUBMIT: 'DEBARK_SUBMIT'
}

export const CONFIRM = {
  ERROR: 'CONFIRM_ERROR',
  ROUTE: 'CONFIRM_ROUTE',
  MOUNT: 'CONFIRM_MOUNT',
  FETCH: 'CONFIRM_FETCH',
  STORE: 'CONFIRM_STORE',
  CHANGE: 'CONFIRM_CHANGE',
  SUBMIT: 'CONFIRM_SUBMIT'
}

export default {
  ALPHA,
  OMEGA,
  EMBARK,
  DEBARK,
  CONFIRM
}
